# Configurar previamente auth con JWT (leer README.md)
# Reemplazar `...` en `Authorization: Bearer ...` por el token recibido
# Revisar que el número de puerto coincida con el .env
# Revisar que no haya trailing commas en el JSON :p

# LOGUEO DE USUARIO DE PRUEBAS
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "nombre_usuario": "admin@test.com",
  "contrasenia": "test"
}

###

# OBTENER TODAS LAS RESERVAS (omitiendo las inactivas)
GET http://localhost:3000/api/v1/reservas
Authorization: Bearer ...

###

# OBTENER TODAS LAS RESERVAS (incluyendo las inactivas)
GET http://localhost:3000/api/v1/reservas?incluirInactivos=true
Authorization: Bearer ...

###

# OBTENER UNA RESERVA ESPECÍFICA POR ID
GET http://localhost:3000/api/v1/reservas/1
Authorization: Bearer ...

###

# CREAR UNA RESERVA
# MySQL espera el formato YYYY-MM-DD
# Los ID del salon, usuario y turno deben existir previamente en la BD
# Requiere autorización por rol
POST http://localhost:3000/api/v1/reservas
Content-Type: application/json

Authorization: Bearer ...

{
  "fecha_reserva": "2025-12-11",
  "salon_id": 2,
  "usuario_id": 1,
  "turno_id": 1,
  "servicios": []
}


###

# ACTUALIZAR UNA RESERVA
PUT http://localhost:3000/api/v1/reservas/14
Content-Type: application/json
Authorization: Bearer ...
{
  "tematica": "Autos"
}


###
# ELIMINAR UNA RESERVA
DELETE http://localhost:3000/api/v1/reservas/1
Authorization: Bearer ...