# Revisar que el número de puerto coincida con el .env

# OBTENER TODOS LOS SERVICIOS (omitir los inactivos)
GET http://localhost:3000/api/v1/servicios

###
# OBTENER TODOS LOS SERVICIOS (incluyendo los inactivos)
GET http://localhost:3000/api/v1/servicios?incluirInactivos=true


###

# OBTENER UN SERVICIO ESPECÍFICO POR ID
GET http://localhost:3000/api/v1/servicios/1


###

# CREAR UN SERVICIO
POST http://localhost:3000/api/v1/servicios
Content-Type: application/json

{
  "descripcion": "Peluca",
  "importe": 15000
}

###

# ACTUALIZAR UN SERVICIO
PUT http://localhost:3000/api/v1/servicios/
Content-Type: application/json

{
  "descripcion": "Corte y barba",
  "importe": 7500
}


###
# ELIMINAR UN SERVICIO
DELETE http://localhost:3000/api/v1/servicios/4
